# Generated by Django 5.1.7 on 2025-04-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='returns',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
